export const SUBMIT_REGISTRATION_EPIC = 'SUBMIT_REGISTRATION_EPIC';
export const SUBMIT_REGISTRATION_SUCCEEDED = 'SUBMIT_REGISTRATION_SUCCEEDED';
export const SUBMIT_REGISTRATION_FAILED = 'SUBMIT_REGISTRATION_FAILED';
export const SUBMIT_REGISTRATION_CANCEL = 'SUBMIT_REGISTRATION_CANCEL';
export const SUBMIT_REGISTRATION_READING = 'SUBMIT_REGISTRATION_READING';
